### ISSUE TITLE
Shift spell for unarmed doesnt let you attack anymore

### ISSUE THREAD

**Issue by JordanBiego** [mfoltz/Bloodcraft#10]
When i set up a shift spell and use the .shift, the spell works fine, but then i cant use the normal attack anymore.
Idk, maybe im missing something?

**Comment by mfoltz** [comment]
like normal primary attack for unarmed? seems alright testing just now

**Comment by JordanBiego** [comment]
Not only normal primary attack for unarmed, but for all weapons.
I put the id manually on the config for the shift spell, i didnt find a better way trough commands, maybe is something to do with the type of spell i put there?

**Comment by mfoltz** [comment]
Quite possibly. Try removing it or changing to one that works from the defaults and see if that does the trick

**Comment by mfoltz** [comment]
Do note that if this is happening because of a buff the spell gave you it would need to be manually removed. KindredCommands can show you your present buffs and has commands to debuff specific ones from your character if that is the case. Closing this for now
