### ISSUE TITLE
Error in using version 0.9.1.0? Why?

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#11]
![Uploading 135.png…]()

**Comment by tongren66** [comment]
[Message:     Unity] EOS.Session - Entering ModifySessionAsync!
[Error  :Bloodcraft] Exited DeathEventListenerSystem hook early: System.NullReferenceException: Object reference not set to an instance of an object.
   at Bloodcraft.Patches.DeathEventListenerSystemPatch.OnUpdatePostfix(DeathEventListenerSystem __instance)
[Message:     Unity] EOS.Session - Entering ModifySessionAsync!
What is this mistake?

**Comment by tongren66** [comment]
[Message:     Unity] EOS.Session - Entering ModifySessionAsync!
[Error  :Bloodcraft] Exited DeathEventListenerSystem hook early: System.NullReferenceException: Object reference not set to an instance of an object.
   at Bloodcraft.Patches.DeathEventListenerSystemPatch.OnUpdatePostfix(DeathEventListenerSystem __instance)
[Message:     Unity] EOS.Session - Entering ModifySessionAsync!
What is this mistake?

**Comment by mfoltz** [comment]
restart server, that means mod didn't initialize correctly for whatever reason

**Comment by tongren66** [comment]
The server is restarted, and this error still occurs.

**Comment by mfoltz** [comment]
not sure then. if it isn't causing issues I wouldn't worry about it, will look into it when I get the chance
