### ISSUE TITLE
Familiars [bug][feedback]

### ISSUE THREAD

**Issue by Djizox** [mfoltz/Bloodcraft#12]
[Bugs]
Familiars does nothing in damage the first many level depending on their actual mob lvl. if getting a familiar that is spawned in the world is lvl 80 it does almost nothing in damange until that lvl. and that takes a looooong time from 1.  quite sad. 

.sf [level] command does not work. (yeah tryed rebind)

[feedback]
would be awesome/fun if they size scaled to level. so when max lvl they would be 100% size. configurable.

Familiar duels.

**Comment by mfoltz** [comment]
They aren't really supposed to do a lot of damage until they're leveled up, kind of the point to keep them from being blatantly overpowered. The command is '.sfl [Level]', not '.sf [Level]'. Pretty sure they already fight each other.

**Comment by Djizox** [comment]
oh okay. a typo bug then :D it does say .sf 
![billede](https://github.com/mfoltz/Bloodcraft/assets/11280026/bb222b96-e670-42c8-9c33-0304f35d7f18)

**Comment by mfoltz** [comment]
thanks lol, .help in game should display it correctly but updated the readme to be consistent
