### ISSUE TITLE
Commands/Mod not working properly after Update

### ISSUE THREAD

**Issue by Duskmire** [mfoltz/Bloodcraft#13]
Hello and sorry to be a bother once again,

To clarify, my gear level /character level is still properly being recorded after the update, with it dropping down to 0 given that I haven't killed anything yet. However after updating to 0.9.2 none of server chat commands appear to be working any longer, with .lock doing nothing (not even an error message). I am presently trying to figure out if there is something that I missed to try and get it working once again, but any advice would me much appreciated.

**Comment by Duskmire** [comment]
At present I am going to be trying to uninstall and reinstall the mods to hopefully fix the issue.

**Comment by mfoltz** [comment]
if using a mod manager that's probably the culprit although I'm still not quite sure what's up with that. reinstalling tends to work, if still no luck check out the console log and see if they're anything telling

**Comment by mfoltz** [comment]
One solution might be removing the Bloodcraft folder, see if it loads correctly then, and if so can move the old ones back after.

**Comment by Duskmire** [comment]
Thank you, the reinstall worked to get things working again but every update has been resetting our weapon levels.

**Comment by mfoltz** [comment]
those are no longer being visually changed in latest versions. if any weapons are affected from an older version players can use '.rwl'

**Comment by mfoltz** [comment]
going to close this for now, feel free to reach out if you experience any other issues.
