### ISSUE TITLE
Grouping. [feedback]

### ISSUE THREAD

**Issue by Djizox** [mfoltz/Bloodcraft#15]
i have hoped that using grouping also allowed for not being able to damage eachother like a clan member. but can only be used with the leveling system. right now i only use the familiar and hopefully grouping parts. 
would that even be possible?

**Comment by Djizox** [comment]
also if possible use wave to get dead familiars back insted of typing command all the time?

**Comment by mfoltz** [comment]
grouping is just for exp share at the moment but will be changing to alliances soon (players in same alliance will be permitted in raided territories based on if in alliance with raiders/owners) no damage is kind of a whole different thing code-wise but will see about including that. state control for familiars is very important to prevent buggy behavior and/or duplicates, there's not really a way to specify a number when waving as is necessary when using '.bind #' either. maybe at some point in the future
