### ISSUE TITLE
Unarmed level stuck [Bug]

### ISSUE THREAD

**Issue by Djizox** [mfoltz/Bloodcraft#18]
It's a nice feature if needed, but it would be nice if i could manage a setting for it. still wanna need it to lower gear lvl when using lower gear. i use this when helping lower gear players without doing it "powerfully". 

![billede](https://github.com/mfoltz/Bloodcraft/assets/11280026/1ac11c1e-8a80-48b2-97cd-6a70cda325c5)

**Comment by mfoltz** [comment]
any particular reason you can't take off armor pieces or magic source instead?

**Comment by mfoltz** [comment]
besides that, this is not a bug (intended functionality), and 'issues' on GitHub is not the correct place to submit things you personally want changed in the mod.
