### ISSUE TITLE
Alliance [Feedback]

### ISSUE THREAD

**Issue by Djizox** [mfoltz/Bloodcraft#19]
Make it so they have to accept the alliance invite and not just toggle auto accept for all invites. 
possible shortcut can be. .aai .acceptallianceinvite & .dai declineallianceinvite

**Comment by mfoltz** [comment]
I have a hard time imagining anyone being inundated with so many invites that it's an issue to toggle on, get invited by the person you're coordinating with, then toggle it back off. recent iterations will automatically toggle it off after accepting an invite as well.
