### ISSUE TITLE
Ancestral Forge Interactions

### ISSUE THREAD

**Issue by Bob-Codam** [mfoltz/Bloodcraft#23]
Hello, loving the mod, keep up the great work! 
I have noticed that the ancestral forge does not receive the blacksmithing level durability bonus. Not sure if this is just for the legendary ancestral weapon variants or not. Cheers!

**Comment by mfoltz** [comment]
can't think of any reason it wouldn't be applying to that, will take a look

**Comment by mfoltz** [comment]
should be fixed in latest
