### ISSUE TITLE
PS5 .shift command

### ISSUE THREAD

**Issue by ofgirichardsonb** [mfoltz/Bloodcraft#28]
Hi,

I've succeeded in setting up the Bloodcraft mod on a PS5 server, but there's some difficulty getting certain settings right. First, I'd like to use the .shift command and map it to R3 on PS5, and second, I'd like to ensure that familiars cannot damage other players under any circumstance, perhaps by preventing holy and fire damage from familiars? Can you provide some insight on how this might be accomplished on a PS5 server?

Thanks,
Brian

**Comment by mfoltz** [comment]
nothing to do about fire damage at the moment but the rest is configurable. no idea how to do anything for this game on PS5 so that's all you lol

**Comment by mfoltz** [comment]
going to close this for now.
