### ISSUE TITLE
Familiars can bug a spot in the castle, when it happens, you can no longer build anything in that specific spot.

### ISSUE THREAD

**Issue by Charolas** [mfoltz/Bloodcraft#29]
An easy way to reproduce the bug is to:

Summon a familiar, then toggle it somewhere, the last place it was will be bugged, and we will no longer be able to place items on it, however, this is a temporary bug. 

The issue lies when that said familiar is dismissed badly, such as fam reset or unbind without it being toggled on again.

Summon familiar, toggle it off, fam reset, and done. 

That place will bug and we will never be able to construct there again.

This is not entirely game-breaking, but eventually becomes, as in various spots in your castle plot will be just not constructible anymore.

**Comment by Charolas** [comment]
I think a good way to solve this issue on current servers and saves would be to find a way to allow famreset to reset those bugged spots as well. Then it wouldn't be needed to restart servers that have too much of this bug.

**Comment by mfoltz** [comment]
this appears to be fixed now (not on Thunderstore yet, possibly later today) but reset fams literally destroys the entities involved and that should have been taking care of it anyway. no idea why it wasn't but shouldn't be an issue any longer
