### ISSUE TITLE
Crafting does not level professions since 1.0 upgrade

### ISSUE THREAD

**Issue by ofgirichardsonb** [mfoltz/Bloodcraft#30]
I started a server (PS5) on Bloodcraft 0.9.4. When the 1.0 version came available, I upgraded to it. However, since that upgrade, it appears that we no longer receive profession experience for crafting. I have enabled profession logging and crafted various things in various professions (alchemy, tailoring, blacksmithing), and have received no experience for any of it. On the other hand, gathering professions seem to work correctly. Please advise as to the diagnostic information I may provide for you to look into this further.

**Comment by mfoltz** [comment]
been long enough since 1.0.0 I don't really remember if I had any issues with that when testing but looks fine now and will be updating Thunderstore later today, please reopen if the issue persists after the new version
