### ISSUE TITLE
Classes does nothing when I choose a class since 1.0 version

### ISSUE THREAD

**Issue by wparanhosm** [mfoltz/Bloodcraft#31]
I already have started a dedicated server with the 1.2.3 version. I enabled the soft sinergy, but when I choose the class, the terminal doesn't works. I did the downgrade to the 1.0 version and this issue doesn't happened 

![image](https://github.com/user-attachments/assets/4c34e065-d6d6-4005-8285-3eb86f3abd9e)

**Comment by andrelu1z** [comment]
Same happened to me yesterday. Had to downgrade the version too. Hope they fix it soon.

**Comment by mfoltz** [comment]
working fine on my end. is there anything in console when you try this? are there any other commands not working?

**Comment by wparanhosm** [comment]
I am using the Steam version, i put just the soft sinergy to true and try those 2 commands

**Comment by mfoltz** [comment]
unfortunately that's not really enough information for me to try and replicate this

**Comment by mfoltz** [comment]
Similar issues others were having seem to be fixed in 1.2.4, feel free to reopen if this persists but closing for now.
