### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Niconoko** [mfoltz/Bloodcraft#32]
Is this compatible with XP Rising? SInce it has level system as well? Or player has to choose which one to play with? (´・ω・｀)

**Comment by mfoltz** [comment]
can't use systems from both mods that would obviously conflict but in general, yes.

**Comment by Niconoko** [comment]
Thx for the reply, but again, me need some sort of visual how to set up or use spells, me so confused. (´- ω  -｀)
