### ISSUE TITLE
Unarmed? Extra Slots? Shift?

### ISSUE THREAD

**Issue by Niconoko** [mfoltz/Bloodcraft#33]
Me not understand how these work or how to equip spells, me tried to read the info still don't get them, any visual aid or proper tutorial? (´・ω・｀)ll

**Comment by mfoltz** [comment]
-use the spell lock command
-drag spells from book to spots on bar
-use command again
-switch to unarmed

assuming requirements are met as configured for class spells, make sure shift is toggled to 'enabled' via the command and after picking a spell with '.class csp 1-4' it will be available on shift after swapping weapons and on unarmed. if you're still experiencing difficulties would recommend visiting the modding discord for further assistance https://discord.gg/bSf4DnXu
