### ISSUE TITLE
Mod Not Appearing to Work

### ISSUE THREAD

**Issue by Duskmire** [mfoltz/Bloodcraft#4]
Hello and sorry if this is simply something that I missed when downloading the mod.

However when me and a friend were working on trying to set up the mod for our multiplayer world we noticed that the commands to activate the mod were not present and came back with an error code every time we tried to input them to activate the mod. If this is simply due to the mod being purely for servers and unable to function on a local hosted game that is understandable, but we wanted to make sure this wasn't simply a case of us not having the mod properly installed.

To be exact the error I am given when typeing: ToggleSetting LevelingSystem True is
Error> No valid Setting Identifier supplied.
We have also tried it without the ToggleSetting and received a return of Command Not Found.

Thank you for whatever insight you are able to give into this issue.

**Comment by mfoltz** [comment]
youll need server launch fix as well if you don't already have that but those will be config values you change in the file outside the game manually, feel free to reach out on the modding discord if you need help!

**Comment by Duskmire** [comment]
Is it potentially possible to run this in a solo world, or is it purely only available for servers?

**Comment by Duskmire** [comment]
Thank you, we hadn't even realized the Server Launch Fix as a seperate mod and I am sorry about our confusion. Unfortunately that mod is now giving us troubles, but thank you for the help you have given so far as we will search for the solutions to that mod in the proper channels elsewhere.
