### ISSUE TITLE
Quest target not updating

### ISSUE THREAD

**Issue by archenovalis** [mfoltz/Bloodcraft#40]
Found two situations where quest target would not update.

Killing Crossbow Skeletons needed me to find the specific skeleton.
- Modified eclipse to display target level https://github.com/mfoltz/Eclipse/pull/3

Then I found that some Cultist kills didn't count.
- Modified bloodcraft to compare kill with name instead of guid and required that the kill's level be equal or higher. #39

**Comment by mfoltz** [comment]
yes, credit is based on the prefab and not the name. '.quest daily/weekly' shows the general name for the unit along with the prefab that gives credit and '.quest t daily/weekly' will provide direction to the nearest unit with that prefab that gives credit for the quest. Don't intend on providing credit based on the general localized unit name but will review the changes for displaying level
