### ISSUE TITLE
Question about synergies and spells.

### ISSUE THREAD

**Issue by BracketMaan** [mfoltz/Bloodcraft#41]
In the config there are listed weapon synergies, do these refer to weapons (sword, axe) or the stats from weapon expertise system (crit chance, crit dmg)?

```
## Blood Knight weapon synergies.
# Setting type: String
# Default value: 0,3,5,6
BloodKnightWeapon = 0,3,5,6
```

Where can I find a map to decode what those numbers mean?

For spells that can be shown with:
`class lsp [class]`
Are they unlocked only by prestiging and available only on shift?

What on-hit buffs does each class get and where can I learn configure them?

**Comment by mfoltz** [comment]
Use '.wep lst' and '.bl lst' in game and the numbers in the list (starting from 0) will correspond to the stats from 0-11.
Unless you set prestige requirement to 0, yes, and yes on shift.
They apply the debuff from their spell school (bloodknight leech, demonhunter static, etc) to enemies as a % chance on melee/spell hits and if that debuff is already present will instead buff the user with the respective T08 necklace effect. You don't configure them.

**Comment by BracketMaan** [comment]
Ah I see, thanks! One more thing, are blood legacies supposed to be active when a particular blood was last drank? I'm unsure because weapon cooldown recovery, cc reduction and dmg reduction do not appear to work.

**Comment by mfoltz** [comment]
they only apply when you have that blood equipped yeah
