### ISSUE TITLE
few questions if you have the time. 

### ISSUE THREAD

**Issue by Orionox** [mfoltz/Bloodcraft#43]
1. Does minion damage as a stat affect familiar? will it affect minions summoned by familiars?
2. What does blood efficiency as a stat do? is it the same as the blood ability that says, "Boosts all above effects by 25%"? if so, does it stack with that or do stats from blood have the same limitation of stats from classes where they don't stack with blood values.

**Comment by mfoltz** [comment]
1. maybe! easiest way to tell would be experimenting and keeping track of damage dealt when that bonus is applied versus not applied.
2. it does the same thing the vampiric brew does sort of. can kind of pretend like it's an increase in the quality of the blood, doesn't have any limits I'm aware of

**Comment by mfoltz** [comment]
closing for now.
