### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by happywolf** [mfoltz/Bloodcraft#46]
I downloaded the version from Thunderstore and I get it starting in game but I cannot set anything up. Keeps saying X function is disabled.

**Comment by mfoltz** [comment]
need to turn things on in the config file if that hasn't been done yet.

**Comment by happywolf** [comment]
If its the .cfg one inside server and plugin folder. I did change all those settings to "true"

**Comment by mfoltz** [comment]
sounds like it didn't stick then. would double-check changes are persisting as made.

**Comment by happywolf** [comment]
Is it the "io.zfolmt.Bloodcraft.cfg" in Config that needs enabling? 
I changed everything to true that were false.

**Comment by happywolf** [comment]
After reinstalling it and changing to true. It suddenly started working I guess.
