### ISSUE TITLE
How to set up skills for unarmed in single player

### ISSUE THREAD

**Issue by JordanBiego** [mfoltz/Bloodcraft#5]
The mod is working fine so far, but when i reach the level that unlocks the spell slot dor unarmed, ive got nothing, so i saw in the config file for weapons and see that there's a file called sanguimancy_spell ( or something like that) and both slots is set to zero, so i wonder, how can i set the spells i want? What do i need to change in this file? 
Im trying to figure it out the spells id, maybe its something i can put there, but didn't find any id that works.
Can you guys help me with this? Ill be glad

**Comment by JordanBiego** [comment]
.lock? Its a command for the framework that uses right? I cant access it, im not running a dedicated server. Can you elaborate please?

**Comment by mfoltz** [comment]
you just use the chatlog. if you didn't have VCF already the mod wouldn't load, all the commands should appear with .help

**Comment by JordanBiego** [comment]
I'll try the chatlog, i have VCF, but the BepInEx says this when loading:
`[Info   :   BepInEx] Loading [VampireCommandFramework 0.9.0]
[Message:VampireCommandFramework] Note: Vampire Command Framework is loading on the client but only adds functionality on the server at this time, seeing this message is not a problem or bug.`

So, i guess only works if i make a dedicated server, which is a thing i don't really wanna do just to play solo.

In any case, if the chatlog doesn't work, can i put the id manually of what i want? In fact, which id should i put it and how?
I found this site, that has the hashes for the abilities and stuff, but there's a lot of things that could be usable: 
https://vrising.gaming.tools/abilities/ab_blood_bloodrite_abilitygroup like this one for example, this is the object: 
`{
  "prefabGuid": 1191439206,
  "prefabName": "AB_Blood_BloodRite_AbilityGroup",
  "managedAbilityGroupData": {
    "name": "6b767c92-3a0b-4ce9-a236-fd58436addf4",
    "description": {
      "key": "a259006a-5af9-482c-8a78-235cf05e9ea8",
      "parameterIndex": 3,
      "parameterCount": 3
    },
    "icon": "Stunlock_Icon_Ability_Spell_Shadow_ShadowDance"
  },
  "abilityGroupState": {
    "groupId": 1191439206,
    "slotIndex": 6
  },
  "abilityGroupStartAbilitiesBuffer": [
    {
      "prefabGUID": 863435029
    }
  ],
  "localizedStringBuilderParameter": [
    {
      "key": "damage",
      "value": "100",
      "numericFormat": "Percent100"
    },
    {
      "key": "immaterialduration",
      "value": "1.2",
      "numericFormat": "Default"
    },
    {
      "key": "duration",
      "value": "1.5",
      "numericFormat": "Default"
    },
    {
      "key": "damage",
      "value": "100",
      "numericFormat": "Percent100"
    },
    {
      "key": "immaterialduration",
      "value": "1.2",
      "numericFormat": "Default"
    },
    {
      "key": "duration",
      "value": "1.5",
      "numericFormat": "Default"
    }
  ],
  "vBloodAbilityData": {
    "abilityType": "Defensive",
    "abilitySchool": "Blood",
    "abilityTooltipType": "None"
  }
}`

I assume i would need to use the `prefabGuid` ?
Sorry for the bucket load of questions. hehe

**Comment by JordanBiego** [comment]
Just an update, it worked using the chatlog, i figured it out!
Awesome!
Nice work man, this mod completely changes the gameplay, awesome!

**Comment by mfoltz** [comment]
glad to hear it! will close issue now
