### ISSUE TITLE
Cool mod, man. But why don't you add a function about letting the servant follow players?

### ISSUE THREAD

**Issue by AstrayMephisto** [mfoltz/Bloodcraft#6]
You can add this function, servants which be converted already can turn into familiars. Then we can go fight with our servants. If we can go with 2 or 3 servants to make up a squad will be great too. What kind of master am I if servants can't even follow me? A lot of players waited for this function for years. I love your mod, friend.

**Comment by AstrayMephisto** [comment]
I found your familiar system is better than the original servant system. I think you can add a fuction about converting the familiar to an original servant at coffins. Also it will be cool to rename the familiar like pokemon.

**Comment by mfoltz** [comment]
servants and familiars are preeeetty separate functionality-wise even if they look similar on the surface. for a variety of reasons familiars can't be converted into servants, have looked into it before but introduces extremely buggy behavior that's hard to manage and the two are extremely different when it comes to the code and systems in-game that are managing them. renaming familiars is on the eventually list
