### ISSUE TITLE
Unarmed Set-Up

### ISSUE THREAD

**Issue by Duskmire** [mfoltz/Bloodcraft#7]
Hello and sorry to be a bother again, I have finally got the mod itself working as I had hoped aside from one slight detail. After reaching level 25 in Unarmed I tried to bind the spells I wished with .lock, however when I did so I couldn't see how to pick the spells I wished and so I wanted to check and see if I might be doing something wrong.

**Comment by Duskmire** [comment]
Nevermind, I forgot to re-equip unarmed.

**Comment by mfoltz** [comment]
lol no worries
