### ISSUE TITLE
On the new version of the familiar

### ISSUE THREAD

**Issue by tongren66** [mfoltz/Bloodcraft#8]
Hi, hello. Today, I used the new version of MOD familiar, and there was a problem. I called prefabGUID: Gattler,Lightning Protector. It's time for the server to crash directly. I don't know if you can fix this problem, so I'm here to ask. thank you

**Comment by tongren66** [comment]
prefabGUID: -884401089,1655577903

**Comment by mfoltz** [comment]
think I see why this could be happening, will make change and test later

**Comment by mfoltz** [comment]
this should be good now, let me know if it comes up again
